name: Print Message

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to print' 
        required: true
        default: 'Hello, World!'

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "${{ github.event.inputs.message }}"
